# \\  # Backslash (\)
# \' #Single- quote (')
# \" #Double- quote (")
# \a #ASCII bell (BEL)
# \b #ASCII backspace (BS)
# \f #ASCII formfeed (FF)
# \n #ASCII linefeed (LF)
# \N{#name} # Character named name in the Unicode database (Unicode only)
# #Character named name in the Unicode database (Unicode only)
# \r #ASCII carriage return (CR)
# \t #ASCII horizontal tab (TAB)
# \uxxxx #Character with 16- bit hex value xxxx (Unicode only)
# \Uxxxxxxxx #Character with 32- bit hex value xxxxxxxx (Unicode only)
# \v A#SCII vertical tab (VT)
# \ooo #Character with octal value oo
a = "\x45"
print(a)